[project]
id = "vatalique-app"
name = "Vatalique Elite AI Solutions"

[build]
builder = "gcr.io/buildpacks/builder:google-22"

[[build.env]]
name = "GOOGLE_NODEJS_VERSION"
value = "20"

[[build.env]]
name = "GOOGLE_ENTRYPOINT"
value = "npm run start:prod"
